os:
  editPreset: "nvim"
git:
  allBranchesLogCmds:
    - "git log --all --decorate --oneline --graph --color=always"
  diffRenderers:
    - command: delta --dark --paging=never
keybinding:
  commits:
    moveUpCommit: [<ctrl-up>]
    moveDownCommit: [<ctrl-down>]
