# Settings
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g extended-keys on

set -g status on
set -g status-position top
set -g base-index 1
set -s escape-time 0
set -g history-limit 1000000
set -g renumber-windows on
set -g set-clipboard on
set -g mouse on

unbind C-b
set -g prefix C-Space

bind M-r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# Keybindings
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind -r j select-pane -L
bind -r k select-pane -D
bind -r l select-pane -U
bind -r \; select-pane -R
bind -r p last-pane

bind c new-window -c "#{pane_current_path}"
bind -r C-w last-window
bind r command-prompt "rename-window -- '%%'"
bind R command-prompt "rename-session -- '%%'"

bind -r C-c new-session
bind -r C-s "switch-client -l"  # last session

# vim mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle \; send -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi C-y send-keys -X copy-pipe-and-cancel "wl-copy"

# Start from 1 in session picker
# https://unix.stackexchange.com/a/755474/346920
bind-key s choose-tree -ZsK '#{?#{e|<:#{line},9},#{e|+:1,#{line}},#{?#{e|<:#{line},35},M-#{a:#{e|+:97,#{e|-:#{line},9}}},}}'

# Theme
set -g status-left "#{?client_prefix,#[fg=black#,bg=blue],#[fg=blue#,bg=default]}   #S "
set -g status-left-length 25
set -g status-right "#[fg=default,dim,bg=default] #{pane_current_path}"
set -g status-right-length 50
set -g status-justify absolute-centre
set -g status-style bg=default
set -g window-status-current-format '#[fg=magenta,bold,bg=default]  #I #W'
set -g window-status-format '#[fg=default,dim,bg=default] #I #W'
set -g window-status-last-style 'fg=default,bg=default'
set -g message-command-style bg=default,fg=gray
set -g message-style bg=default,fg=gray
set -g mode-style bg=black,fg=default
set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'

# Plugins
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-save 'S'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
# set -g @plugin 'whame/tmux-modal'

run '~/.config/tmux/plugins/tpm/tpm'
