#!/bin/sh

# Generated by arandr Save As

xrandr --output DP-0 --off --output DP-1 --off --output DP-2 --mode 3440x1440 --pos 0x0 --rotate normal --output DP-3 --off --output DP-4 --mode 1920x1200 --pos 3440x0 --rotate left --output DP-5 --off
