#!/bin/bash

current_workspace=$(i3-msg -t get_tree | jq -r "recurse(.nodes[]) | select(.type == \"workspace\" and ([recurse((.nodes, .floating_nodes)[])] | any(.focused))) | .name")
floating_workspace="F${current_workspace}"

if i3-msg -t get_tree | jq -e "recurse(.nodes[]) | select(.type == \"workspace\" and .name == \"$current_workspace\") | .floating_nodes | length > 0"; then
  i3-msg "[workspace=$current_workspace floating] move to workspace $floating_workspace"
else
  i3-msg "[workspace=$floating_workspace] floating enable"
  i3-msg "[workspace=$floating_workspace floating] move to workspace $current_workspace"
  i3-msg focus floating
fi
