[buildPlans.Garosevka]
family = "Garosevka"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

[buildPlans.Garosevka.variants.design]
capital-k = "curly-serifless"
a = "single-storey-earless-rounded-tailed"
b = "toothless-corner"
d = "toothless-corner-serifless"
g = "earless-corner"
i = "tailed-serifed"
j = "serifed"
k = "curly-serifless"
l = "tailed-serifed"
m = "earless-corner-double-arch"
n = "earless-corner-straight"
p = "earless-corner"
q = "earless-corner"
r = "earless-corner"
t = "standard-short-neck"
u = "toothless-corner"
y = "straight-turn"
asterisk = "turn-hex-low"
paren = "flat-arc"
brace = "straight"
number-sign = "slanted"
dollar = "open"
cent = "open"
percent = "rings-continuous-slash"
lig-ltgteq = "slanted"
ascii-single-quote = "straight"

[buildPlans.Garosevka.weights.thin]
shape = 100
menu = 100
css = 100

[buildPlans.Garosevka.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.Garosevka.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.Garosevka.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.Garosevka.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Garosevka.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"